Make commands for main wagon script
We now have:
+ usage
+ load (which requires source)
+ intall

diff --git a/bin/wagon b/bin/wagon
--- a/bin/wagon
+++ b/bin/wagon
@@ -1,25 +1,71 @@
 #!/bin/bash
 
-ver="_$(echo $1 | sed s/[.]/_/)"
-rocktree="$(pwd)/.rocktree"
-config_file="$rocktree/config.lua"
+usage()
+{
+  echo "Usage:"
+  echo "  $0 <command>"
+  echo "Or, to load the wagon:"
+  echo "  source $0 load <lua version>"
+}
 
-echo "Rocktree: $rocktree"
-echo "Config file: $config_file"
+set_wagon_env()
+{
+  if [ $# -lt 1 ]; then
+    echo "[wagon] Missing lua version to load"
+    usage
+    exit
+  fi
 
-export LUA_PATH$ver="$rocktree/share/lua/$1/?.lua;$rocktree/share/lua/$1/?/init.lua"
+  ver="_$(echo $1 | sed s/[.]/_/)"
+  rocktree="$(pwd)/.rocktree"
+  config_file="$rocktree/config.lua"
+  
+  echo "[wagon] Rocktree loaded at $rocktree"
+  echo "[wagon] Configuration file path: $config_file"
 
-export LUA_CPATH$ver="$rocktree/lib/lua/$1/?.so"
+  export WAGON_ROCKTREE=$rocktree
+  
+  export LUA_PATH$ver="$rocktree/share/lua/$1/?.lua;$rocktree/share/lua/$1/?/init.lua"
+  
+  export LUA_CPATH$ver="$rocktree/lib/lua/$1/?.so"
+  
+  export LUAROCKS_CONFIG$ver=$config_file
+  
+  export PATH="$(pwd)/.rocktree/bin:$PATH"
+  
+  mkdir -p $rocktree
+  
+  if [ ! -f $config_file ]; then
+    echo "rocks_trees = { { name='user', root='$rocktree' } }" > $config_file
+  fi
+  
+  echo "[wagon] Wagon has been successfully loaded"
+}
 
-export LUAROCKS_CONFIG$ver=$config_file
+install_deps()
+{
+  ROCKSPEC_PATH=$1
+  if [ $# -lt 1 ]; then
+    ROCKSPEC_PATH=$(ls *.rockspec | head -n 1)
+  fi
 
-export PATH="$(pwd)/.rocktree/bin:$PATH"
+  wagon-deps.lua $ROCKSPEC_PATH
+}
 
-mkdir -p $rocktree
-
-if [ ! -f $config_file ]; then
-  echo "rocks_trees = { { name='user', root='$rocktree' } }" > $config_file
+if [ $# -lt 1 ]; then
+  usage
+  exit
 fi
 
-echo "Lua rocktree set up"
+case $1 in
+    load )    set_wagon_env $2
+              ;;
+    help )    usage
+              exit
+              ;;
+    install ) install_deps $2
+              ;;
+    * )       usage
+              exit 1
+esac
 
